package model;
// Generated 2020�~11��13�� �W��12:07:06 by Hibernate Tools 5.4.21.Final

/**
 * Accommodation generated by hbm2java
 */
public class Accommodation implements java.io.Serializable {

	private int id;
	private Location location;
	private String baBname;
	private Integer city;
	private String description;
	private String picture;
	private String address;

	public Accommodation() {
	}

	public Accommodation(Location location) {
		this.location = location;
	}

	public Accommodation(Location location, String baBname, Integer city, String description, String picture,
			String address) {
		this.location = location;
		this.baBname = baBname;
		this.city = city;
		this.description = description;
		this.picture = picture;
		this.address = address;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Location getLocation() {
		return this.location;
	}

	public void setLocation(Location location) {
		this.location = location;
	}

	public String getBaBname() {
		return this.baBname;
	}

	public void setBaBname(String baBname) {
		this.baBname = baBname;
	}

	public Integer getCity() {
		return this.city;
	}

	public void setCity(Integer city) {
		this.city = city;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getPicture() {
		return this.picture;
	}

	public void setPicture(String picture) {
		this.picture = picture;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

}
