package model;
// Generated 2020�~11��13�� �W��12:07:06 by Hibernate Tools 5.4.21.Final

import java.util.Date;

/**
 * Activity generated by hbm2java
 */
public class Activity implements java.io.Serializable {

	private int fesId;
	private Guide guide;
	private Location location;
	private String fesName;
	private String fesDescription;
	private Date fesDurationStart;
	private Date fesDurationEnd;
	private String picture;
	private Order order;

	public Activity() {
	}

	public Activity(int fesId, String fesName) {
		this.fesId = fesId;
		this.fesName = fesName;
	}

	public Activity(int fesId, Guide guide, Location location, String fesName, String fesDescription,
			Date fesDurationStart, Date fesDurationEnd, String picture, Order order) {
		this.fesId = fesId;
		this.guide = guide;
		this.location = location;
		this.fesName = fesName;
		this.fesDescription = fesDescription;
		this.fesDurationStart = fesDurationStart;
		this.fesDurationEnd = fesDurationEnd;
		this.picture = picture;
		this.order = order;
	}

	public int getFesId() {
		return this.fesId;
	}

	public void setFesId(int fesId) {
		this.fesId = fesId;
	}

	public Guide getGuide() {
		return this.guide;
	}

	public void setGuide(Guide guide) {
		this.guide = guide;
	}

	public Location getLocation() {
		return this.location;
	}

	public void setLocation(Location location) {
		this.location = location;
	}

	public String getFesName() {
		return this.fesName;
	}

	public void setFesName(String fesName) {
		this.fesName = fesName;
	}

	public String getFesDescription() {
		return this.fesDescription;
	}

	public void setFesDescription(String fesDescription) {
		this.fesDescription = fesDescription;
	}

	public Date getFesDurationStart() {
		return this.fesDurationStart;
	}

	public void setFesDurationStart(Date fesDurationStart) {
		this.fesDurationStart = fesDurationStart;
	}

	public Date getFesDurationEnd() {
		return this.fesDurationEnd;
	}

	public void setFesDurationEnd(Date fesDurationEnd) {
		this.fesDurationEnd = fesDurationEnd;
	}

	public String getPicture() {
		return this.picture;
	}

	public void setPicture(String picture) {
		this.picture = picture;
	}

	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

}
