package model;
// Generated 2020�~11��13�� �W��12:07:06 by Hibernate Tools 5.4.21.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Guide generated by hbm2java
 */
public class Guide implements java.io.Serializable {

	private int id;
	private String name;
	private String description;
	private Integer gender;
	private Set activities = new HashSet(0);

	public Guide() {
	}

	public Guide(int id) {
		this.id = id;
	}

	public Guide(int id, String name, String description, Integer gender, Set activities) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.gender = gender;
		this.activities = activities;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getGender() {
		return this.gender;
	}

	public void setGender(Integer gender) {
		this.gender = gender;
	}

	public Set getActivities() {
		return this.activities;
	}

	public void setActivities(Set activities) {
		this.activities = activities;
	}

}
