package model;
// Generated 2020�~11��13�� �W��12:07:06 by Hibernate Tools 5.4.21.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Location generated by hbm2java
 */
public class Location implements java.io.Serializable {

	private int id;
	private String city;
	private String description;
	private String features;
	private Set activities = new HashSet(0);
	private Accommodation accommodation;

	public Location() {
	}

	public Location(int id, String city) {
		this.id = id;
		this.city = city;
	}

	public Location(int id, String city, String description, String features, Set activities,
			Accommodation accommodation) {
		this.id = id;
		this.city = city;
		this.description = description;
		this.features = features;
		this.activities = activities;
		this.accommodation = accommodation;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getFeatures() {
		return this.features;
	}

	public void setFeatures(String features) {
		this.features = features;
	}

	public Set getActivities() {
		return this.activities;
	}

	public void setActivities(Set activities) {
		this.activities = activities;
	}

	public Accommodation getAccommodation() {
		return this.accommodation;
	}

	public void setAccommodation(Accommodation accommodation) {
		this.accommodation = accommodation;
	}

}
