package model;
// Generated 2020�~11��13�� �W��12:07:06 by Hibernate Tools 5.4.21.Final

import java.util.Date;

/**
 * Order generated by hbm2java
 */
public class Order implements java.io.Serializable {

	private int id;
	private Activity activity;
	private Customer customer;
	private Integer customerName;
	private Integer activityName;
	private Date placedDate;
	private Integer price;
	private Date startDate;
	private Date endDate;

	public Order() {
	}

	public Order(Activity activity, Customer customer) {
		this.activity = activity;
		this.customer = customer;
	}

	public Order(Activity activity, Customer customer, Integer customerName, Integer activityName, Date placedDate,
			Integer price, Date startDate, Date endDate) {
		this.activity = activity;
		this.customer = customer;
		this.customerName = customerName;
		this.activityName = activityName;
		this.placedDate = placedDate;
		this.price = price;
		this.startDate = startDate;
		this.endDate = endDate;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Activity getActivity() {
		return this.activity;
	}

	public void setActivity(Activity activity) {
		this.activity = activity;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public Integer getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(Integer customerName) {
		this.customerName = customerName;
	}

	public Integer getActivityName() {
		return this.activityName;
	}

	public void setActivityName(Integer activityName) {
		this.activityName = activityName;
	}

	public Date getPlacedDate() {
		return this.placedDate;
	}

	public void setPlacedDate(Date placedDate) {
		this.placedDate = placedDate;
	}

	public Integer getPrice() {
		return this.price;
	}

	public void setPrice(Integer price) {
		this.price = price;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

}
