package model;
// Generated 2020�~11��13�� �W��12:07:06 by Hibernate Tools 5.4.21.Final

/**
 * Restaurant generated by hbm2java
 */
public class Restaurant implements java.io.Serializable {

	private int id;
	private String name;
	private Integer city;
	private String description;
	private String picture;
	private String address;

	public Restaurant() {
	}

	public Restaurant(int id) {
		this.id = id;
	}

	public Restaurant(int id, String name, Integer city, String description, String picture, String address) {
		this.id = id;
		this.name = name;
		this.city = city;
		this.description = description;
		this.picture = picture;
		this.address = address;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getCity() {
		return this.city;
	}

	public void setCity(Integer city) {
		this.city = city;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getPicture() {
		return this.picture;
	}

	public void setPicture(String picture) {
		this.picture = picture;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

}
